### PR TITLE
Replace adhoc yaml with serde

### PR DESCRIPTION
**Pull request by Ichmed**
first part of #128 

Includes only podman config, will copy the approach for firecracker and/or create generic version for all back ends if approved

Adds lazy_static for config initialization, can be removed if rust version is bumped to one that includes [OnceCell](https://doc.rust-lang.org/stable/std/cell/struct.OnceCell.html)

### CODE REVIEW

**Comment by schaefi** [comment]
@Ichmed thanks for your work and effort. Your coding is great and as we discussed I expected the type of changes that are part of the pull request. On the other side there are also some changes that I wonder about and consider unrelated to the topic and that also turns the pull request into a hard to review state. To be honest I stopped reading at the commit where git told me it's too large diff to be showed by default.

I was sort of ok with the big changes regarding the clippy patch last time but going forward we should not create pull requests that are practically not in a review state. Please avoid

* unnecessary line break changes
* unnecessary white space changes
* changes at code parts not related to the topic
* removal of comment blocks when they are still valid

I also think it makes sense to create commits per responsibility. Like in an object oriented design pattern when a class is usually developed for a single responsibility also the flow of commits in a pull request can follow this style. In this particular case I though it would be useful to structure the set of commits like this

1. Implementation of serde based reading of the yaml such that it can serve as drop in replacement of the adhoc method
2. Changes to the code that uses adhoc yaml, now using the serde based code

That would turn things right and allows for a real review.

Let me know if this makes sense to you

Thanks

**Comment by Ichmed** [comment]
I didn't realize there were so many whitespace changes, I'll setup a new PR with just the content, however this means we should probably set up a rustfmt job like the clippy one to prevent this in the future.

**Comment by Ichmed** [comment]
Also there is not really a good way to do it in two steps, since the ad-hoc version uses indexing, the serde implementation would need to consist of HashMaps or similar, which would then have to be replaced AGAIN when the ad-hoc code is replaced. But maybe i'm misunderstanding what you mean.

**Comment by Ichmed** [comment]
Closed, will open new PR

**Pull request closed without merging**
