### PR TITLE
flake-ctl 2.0

### PR DESCRIPTION
**Pull request by Ichmed**
Initial version of flake-ctl 2.0

I will move from the cobbled together arg parsing to clap before merging, but there are some version problems with clap and ubuntu rust. So please have a look in the meantime

### CODE REVIEW

**Review by isbm — CHANGES_REQUESTED** [review]
Pull request from non-sync'ed fork. This brings again back UPX and other stuff. Please rebase it properly on origin/master and then re-push.

**Comment by Ichmed** [comment]
The clippy error is in firecracker-pilot, i created #165 for that

**Comment by Ichmed** [comment]
> Pull request from non-sync'ed fork. This brings again back UPX and other stuff. Please rebase it properly on origin/master and then re-push.

Where do you see upx in the Makefile?

**Comment by Ichmed** [comment]
deprecated for #166

**Pull request closed without merging**
