### PR TITLE
Robot tests

### PR DESCRIPTION
**Pull request by Ichmed**
Created an inital set of blackbox tests for both flake-ctl and the pilots

Could be used for a github action in the future

### CODE REVIEW

**Comment by schaefi** [comment]
This looks like a great improvement on the testing side, I like it :+1:

**Comment by schaefi** [comment]
As you are running this in an Ubuntu action you could also consider to use the ```spread``` framework. @IsaacJT implemented it as part of the https://github.com/Elektrobit/nemos-images project. In connection with Canonical and EB work it might be a good idea to consistently use the same testing framework. From a technical perspective I can't tell advantages/disadvantages but maybe @IsaacJT has an opinion about it ?

Thanks

**Comment by schaefi** [comment]
> As you are running this in an Ubuntu action you could also consider to use the `spread` framework. @IsaacJT uses  it as part of the https://github.com/Elektrobit/nemos-images project. In connection with Canonical and EB work it might be a good idea to consistently use the same testing framework. From a technical perspective I can't tell advantages/disadvantages but maybe @IsaacJT has an opinion about it ?
> 
> Thanks

**Comment by IsaacJT** [comment]
Hi @schaefi nice to hear from you!

Unfortunately I don't have a lot of context for things that are being tested here, but from a cursory glance Spread could probably do everything in the .robot files, just using shell script rather than with a nice human-readable script. I'm happy to help if you'd like to start looking at Spread.

**Comment by Ichmed** [comment]
Removed the firecracker tests for now.
Imho we should get this merged asap and then add firecracker in a later PR.

**Comment by schaefi** [comment]
> Hi @schaefi nice to hear from you!
> 
> Unfortunately I don't have a lot of context for things that are being tested here, but from a cursory glance Spread could probably do everything in the .robot files, just using shell script rather than with a nice human-readable script. I'm happy to help if you'd like to start looking at Spread.

Hi @IsaacJT thanks for your reply and the offer. I suggest to go with the robot framework for now as @Ichmed already spent some time on it and will also be the one driving it. I also realized that what EB classified and published as EB Corbos Linux has deviated a lot with the effort that you and others put into the project we called "nemos". To be honest for me there are zero connection points anymore between Corbos Linux aka nautilos and nemos. Thus there is probably also zero interest in consistency with tooling and I'm also no longer responsible for anything in that area. So I look at it from the opensource perspective only and there the decision is usually on those who really do the work. In this case it's Michael and I will go ahead with his implementation. Should there be a change towards spread we take the chance and reach out to you :) Thanks much

**Pull request merged**
